import fs from 'fs/promises';
import path from 'path';
import {XMLParser} from 'fast-xml-parser';

// --- TYPE DEFINITIONS for parsing the FileMaker XML structure ---

interface FmField {
	'@_name': string;
	'@_dataType'?: string; // For BaseField
	'@_datatype'?: string; // For Field (Calc)
	'@_comment'?: string;
}

// A table can contain both BaseFields (standard) and Fields (calcs, summaries)
interface FmTable {
	'@_name': string;
	BaseField?: FmField[];
	Field?: FmField[]; // Calculation fields have a different tag name
}

interface FmXml {
	FMSaveAsXML: {
		Structure: {
			Table: FmTable[];
		}
	}
}

/**
 * Maps FileMaker data types to corresponding TypeScript types.
 * @param fmType - The FileMaker data type string.
 * @returns The TypeScript type string.
 */
function mapFmTypeToTsType(fmType: string | undefined): string {
	switch (fmType) {
		case 'Number':
			return 'number';
		case 'Text':
		case 'Date':
		case 'Time':
		case 'Timestamp':
		case 'Container':
			return 'string';
		default: // For unknown or summary types
			return 'any';
	}
}

/**
 * Parses a FileMaker "Save a Copy as XML" file and generates TypeScript definitions.
 * @param xmlFilePath - The full path to the XML file.
 * @param outputDir - The directory where the output file should be saved.
 */
export async function generateTypesFromXml(xmlFilePath: string, outputDir: string): Promise<void> {
	console.log(`[Generator] Reading schema from: ${path.basename(xmlFilePath)}`);

	const xmlContent = await fs.readFile(xmlFilePath, 'utf-8');

	// 1. Parse the XML file content
	const parser = new XMLParser({ignoreAttributes: false, attributeNamePrefix: '@_'});
	const jsonObj = parser.parse(xmlContent) as FmXml;
	const tables = jsonObj.FMSaveAsXML?.Structure?.Table;

	if (!tables || !Array.isArray(tables)) {
		throw new Error('Could not find a valid Table structure in the provided XML file.');
	}

	// 2. Derive the namespace from the filename
	const namespace = path.basename(xmlFilePath, '.xml').replace(/[^a-zA-Z0-9_]/g, '');

	// 3. Generate the interface for each table
	const interfaceStrings = tables.map(table => {
		const tableName = table['@_name'];
		// Combine BaseField and Field arrays into one for processing
		const allFields = [...(table.BaseField || []), ...(table.Field || [])];

		const fieldStrings = allFields.map(field => {
			const fieldName = field['@_name'];
			const comment = field['@_comment'];
			// FileMaker uses two different attribute names for datatype
			const dataType = field['@_dataType'] || field['@_datatype'];
			const tsType = mapFmTypeToTsType(dataType);

			let fieldString = '';
			// Add JSDoc comment if it exists
			if (comment) {
				fieldString += `    /**\n     * ${comment.replace(/\r\n/g, ' ').replace(/\n/g, ' ')}\n     */\n`;
			}
			// Add the property definition, quoting field names for safety
			fieldString += `    "${fieldName}": ${tsType};`;

			return fieldString;
		}).join('\n');

		return `    interface ${tableName} {\n${fieldStrings}\n    }`;
	});

	// 4. Generate the LayoutMap for automatic type inference
	const layoutMapStrings = tables.map(table => {
		const tableName = table['@_name'];
		return `        "${tableName}": ${tableName};`;
	}).join('\n');

	// 5. Assemble the final TypeScript definition file content
	const outputContent = `// Auto-generated by fm-promise-server. Do not edit manually.
// Last generated: ${new Date().toISOString()}

declare namespace ${namespace} {
${interfaceStrings.join('\n\n')}

    interface LayoutMap {
${layoutMapStrings}
    }
}
`;

	// 6. Write the file to the project root
	const outputPath = path.join(outputDir, 'filemaker-types.d.ts');
	await fs.writeFile(outputPath, outputContent);
	console.log(`[Generator] TypeScript definitions written to: ${outputPath}`);
}
